services:
  frontend:
    build: ./frontend
    container_name: marc-os-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=https://api.marc-os.com
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - proxy
      - internal

  backend:
    build: ./backend
    container_name: marc-os-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongodb:27017/marc-os
      - PORT=5000
      - JWT_SECRET=82tRM5#ThhCAuWUwgD!M3sx!DdB4bWm3H2t4q^#kMGnJ4YZJ@h3vUS8HW*59#e*z72nQX6wdA7U5y0YC7W#FEgCjTY9Kk^&NV7Xc@HJDreTq5gSn45R6U*^7c6M$06dkkfMp*Xv^b9DP96Qz@R4ej*b!j@u9&R#HUe598@aVSGUdB2JEYQfg&16Dhw@RJbee^
      - ADMIN_USERNAME=marcadmin
      - ADMIN_PASSWORD=pG%M2M0xtRxUK2PnDfc&G0uV#EXxdSnWkJa9D4Nk3EQ7R90uU6N%#QR*P5ZMf300
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - proxy
      - internal

  mongodb:
    image: mongo:latest
    container_name: marc-os-mongodb
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge
    internal: true 
